# Generated by Django 3.1.3 on 2020-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
