# Generated by Django 3.1.3 on 2020-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
