# Generated by Django 3.1.3 on 2020-11-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reply_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='core.board'),
        ),
    ]
