# Generated by Django 3.1.3 on 2020-11-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201123_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='is_deleted',
        ),
    ]
